#! /bin/sh

bspc config border_width        2
bspc config window_gap          6 

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
bspc config focused_border_color '#cc241d'

bspc monitor -d web code term chat music 6 7 8 9 10

bspc rule -a Firefox desktop=^1
bspc rule -a Emacs state=tiled desktop=^2
bspc rule -a Slack state=tiled desktop=^4

# start audio server
pulseaudio --start

#disable pc speaker
xset -b

# start binding manager
sxhkd&

# open panel &
polybar bar&

compton&
parcellite&
pasystray&
dunst&
emacs&
firefox&
spotify&
